language: python
python:
    - "2.7"
    - "3.6"

install:
    - "pip install -r requirements.txt"
    - "python setup.py install"
script: 
    - "if [[ $TRAVIS_PYTHON_VERSION == 2.7 || $TRAVIS_PYTHON_VERSION == pypy ]]; then py.test test2; else pytest test3; fi"

